spring:
  application:
    name: event-service
  datasource:
    url: jdbc:h2:mem:eventdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false
      path: /h2-console

server:
  port: 8080