spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:h2:mem:ticketdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false
      path: /h2-console

server:
  port: 8081

# External Service URLs (can override via ENV vars or args)
event:
  service:
    url: http://localhost:8080
notification:
  service:
    url: http://localhost:8082
resilience4j:
  circuitbreaker:
    instances:
      ticketServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
